server:
  port: 1222
  servlet:
    context-path: "/banking"

spring:
  datasource:
    url: "jdbc:mysql://localhost/digital_banking_db"
    username: [MySQL Username]
    password: [MySQL Password]
  sql:
    init:
      mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: [Your Mail]
    password: [Your Mail Password]
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
upload:
  file:
    name: "profile-pictures/"

