server:
  port: 1222
  servlet:
    context-path: "/banking"

spring:
  datasource:
    url: "jdbc:mysql://localhost/digital_banking_db"
    username: "root"
    password: "root"
  sql:
    init:
      mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: [your-email]
    password: [your-email-password]
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
upload:
  file:
    name: "profile-pictures/"

